// web_landing/privacies/btd/page.tsx
import React from 'react';
import { Metadata } from 'next';
import { APP } from '../../btd/data';

export const metadata: Metadata = {
  title: `Privacy Policy | ${APP.name}`,
  description: `Official Privacy Policy for ${APP.name} by ${APP.company}. Details on data protection, Google AdMob, RevenueCat, and Firebase analytics.`,
};

export default function PrivacyPolicyPage() {
  return (
    <article className="prose prose-invert max-w-none space-y-6 text-slate-300 text-sm leading-relaxed">
      <div className="border-b border-white/10 pb-4 mb-6">
        <h1 className="text-2xl md:text-3xl font-black text-white">Privacy Policy</h1>
        <p className="text-xs text-slate-400 mt-1">Last Updated: {APP.lastUpdated} | Effective Immediately</p>
      </div>

      <p>
        Welcome to <strong>{APP.name}</strong> (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;), operated by <strong>{APP.company}</strong>. We are committed to protecting your privacy and providing transparent information regarding how data is collected, stored, and utilized when you interact with our Android mobile application and associated web interfaces.
      </p>

      <h2 className="text-lg font-bold text-white mt-6">1. Scope of This Policy</h2>
      <p>
        This Privacy Policy applies to the {APP.name} mobile application (Package: <code>{APP.packageId}</code>) and related online services. By downloading or accessing {APP.name}, you consent to the data practices described herein.
      </p>

      <h2 className="text-lg font-bold text-white mt-6">2. Information We Collect</h2>
      <p>
        We prioritize data minimization. We do not require account registration or collect your physical name, residential address, or government ID numbers. The application processes the following categories of technical data:
      </p>
      <ul className="list-disc pl-6 space-y-2">
        <li>
          <strong>Device &amp; Hardware Diagnostics:</strong> Mobile operating system version, device make/model, CPU architecture, screen resolution, and locale settings. This data is utilized strictly to ensure appropriate layout rendering and localization.
        </li>
        <li>
          <strong>Usage Telemetry &amp; Interaction Events:</strong> Anonymous analytics recording screen visits, match detail views, filter toggles (Safe, Longshots, Goals), and session lengths.
        </li>
        <li>
          <strong>Mobile Advertising Identifiers:</strong> Google Advertising ID (GAID) collected via Google Mobile Ads SDK to facilitate capped frequency ad delivery and fraud detection.
        </li>
        <li>
          <strong>Subscription &amp; Transaction Tokens:</strong> Digital purchase tokens generated by Google Play Billing and processed via RevenueCat to validate VIP access status without exposing user payment card details.
        </li>
      </ul>

      <h2 className="text-lg font-bold text-white mt-6">3. Third-Party Integrations &amp; SDKs</h2>
      <p>
        {APP.name} integrates trusted third-party service providers to deliver essential features:
      </p>
      <ul className="list-disc pl-6 space-y-3">
        <li>
          <strong>Google AdMob (Google LLC):</strong> Serves non-intrusive rewarded and interstitial ads. AdMob may process device identifiers and ad interactions in accordance with Google&rsquo;s Privacy Policy (<code>policies.google.com/technologies/ads</code>).
        </li>
        <li>
          <strong>RevenueCat, Inc.:</strong> Provides receipt validation, entitlement routing, and in-app purchase state synchronization across device sessions. RevenueCat anonymizes customer identifiers.
        </li>
        <li>
          <strong>Firebase (Google LLC):</strong> Provides real-time Crashlytics diagnostics and Firebase Cloud Messaging (FCM) for push alerts regarding upcoming match kickoffs and predictions.
        </li>
      </ul>

      <h2 className="text-lg font-bold text-white mt-6">4. On-Device Local Storage</h2>
      <p>
        Certain preferences are maintained solely within your device’s local memory (via SharedPreferences and encrypted keystore storage). This includes bookmarked matches, unlocked match history, and theme settings. This information never leaves your personal device.
      </p>

      <h2 className="text-lg font-bold text-white mt-6">5. Data Retention &amp; Security Measures</h2>
      <p>
        We utilize transport layer security (TLS 1.3) encryption for all network requests. Analytical data is stored in aggregated, de-identified formats and retained only for periods necessary to improve algorithmic accuracy and resolve technical faults.
      </p>

      <h2 className="text-lg font-bold text-white mt-6">6. Children&rsquo;s Privacy (COPPA)</h2>
      <p>
        {APP.name} is directed to individuals aged 18 or older. We do not knowingly collect personal information from individuals under the age of 13. If you become aware that a child has provided us with personal information, please notify us immediately so we may purge such data.
      </p>

      <h2 className="text-lg font-bold text-white mt-6">7. Your Privacy Rights (GDPR &amp; CCPA)</h2>
      <p>
        Depending on your jurisdiction, you have the right to request access to, correction of, or erasure of any diagnostic data associated with your device identifier. You may reset or limit your Google Advertising ID at any time through Android OS Settings &gt; Google &gt; Ads.
      </p>

      <h2 className="text-lg font-bold text-white mt-6">8. Contact Information</h2>
      <p>
        If you have questions or concerns regarding our privacy practices, please contact our Data Protection Officer at:
      </p>
      <p className="font-semibold text-emerald-400">
        {APP.company}<br />
        Email: <a href={`mailto:${APP.email}`} className="underline">{APP.email}</a>
      </p>
    </article>
  );
}
