// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDScs4kndt8-Hh_UaDkB4GMuCh1fkKmsXQ',
    appId: '1:1083709001383:web:2b656b30b061d972a4d582',
    messagingSenderId: '1083709001383',
    projectId: 'sanitarypad',
    authDomain: 'sanitarypad.firebaseapp.com',
    storageBucket: 'sanitarypad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapYscVQleBPGKnN6A98cWeTMIr2a0jcQ',
    appId: '1:1083709001383:android:1f6cfd2fd891a35aa4d582',
    messagingSenderId: '1083709001383',
    projectId: 'sanitarypad',
    storageBucket: 'sanitarypad.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7vfJ6QvZqiBA9jUAaxWVEAWJniOMtfmo',
    appId: '1:1083709001383:ios:566e9b52c4011266a4d582',
    messagingSenderId: '1083709001383',
    projectId: 'sanitarypad',
    storageBucket: 'sanitarypad.firebasestorage.app',
    androidClientId: '1083709001383-bnjl3ij2bsa8ob7dsc99g9lsr94bga6l.apps.googleusercontent.com',
    iosClientId: '1083709001383-p5gem4rrpe487aa586pkqhqf9gi1s3so.apps.googleusercontent.com',
    iosBundleId: 'com.stsl.codeink.btd',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7vfJ6QvZqiBA9jUAaxWVEAWJniOMtfmo',
    appId: '1:1083709001383:ios:566e9b52c4011266a4d582',
    messagingSenderId: '1083709001383',
    projectId: 'sanitarypad',
    storageBucket: 'sanitarypad.firebasestorage.app',
    androidClientId: '1083709001383-bnjl3ij2bsa8ob7dsc99g9lsr94bga6l.apps.googleusercontent.com',
    iosClientId: '1083709001383-p5gem4rrpe487aa586pkqhqf9gi1s3so.apps.googleusercontent.com',
    iosBundleId: 'com.stsl.codeink.btd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgeOf65eDeKOnz3ixZruH_QHAzhgBxGZw',
    appId: '1:1083709001383:web:5745c6d43b0b9825a4d582',
    messagingSenderId: '1083709001383',
    projectId: 'sanitarypad',
    authDomain: 'sanitarypad.firebaseapp.com',
    storageBucket: 'sanitarypad.firebasestorage.app',
  );
}
